### ISSUE TITLE
haproxy not binding frontend port with backend ports

### ISSUE THREAD

**Issue by hanzlahabib** [docker-library/haproxy#139]
Hi, i just recently started playing with docker world, i tried mocking Load balancing using Docker, Docker-compose and haproxy, 

Issue which i am facing is this: 
I created docker image and started it, things work fine (With no haproxy config)
when i use docker-compose to make use of haproxy load balancing, it serve my application correctly but it don't map to any frontend PORT

as per config, i should be able to listen at PORT 8080 but it don't work, 

**i may be doing something wrong or there is some SElinux / firewall restricting my port binding,** 

here are my config files

`Dockerfile` content

```
FROM node:alpine
RUN pwd
WORKDIR /app
COPY /app .
RUN npm install
CMD ["npm", "run", "start"]

```

`docker-compose.yml` content

```
version : '3'
services:
  lb:
      image: haproxy
      ports: 
          - 8080:8080
      volumes: 
          - ./haproxy:/usr/local/etc/haproxy
  app1:
      image: lb-test
      environment:
          - PORT=1111
  app2:
      image: lb-test
      environment:
          - PORT=2222

```

`haproxy.cfg` content

```
frontend http
    bind *:8080
    mode http
    default_backend http
backend http
    mode http
    server s1 app1:1111
    server s2 app2:2222
```

I have these config on my repo you can fork/clone it from there and test on your end
[github repo link](https://github.com/hanzlahabib/load-balancing-haproxy/tree/non-blocking-haproxy-balancer)

Thank you
