### ISSUE TITLE
HAproxy pods in Kubernetes rapidly consume all available memory

### ISSUE THREAD

**Issue by victor-sudakov** [docker-library/haproxy#179]
I'm trying to run haproxy in a local Kubernetes cluster (kind v0.11.1 go1.17.6 linux/amd64). 

Kubernetes version: Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

I've tried different images: haproxy:2.0.27-buster, haproxy:2.0.27-alpine, haproxy:2.5.1-alpine,  haproxy:2.5.1-bullseye and some others, and the result is always the same: the **haproxy pod rapidly (!) consumes as much memory as limits permit** (and if there is no limit configured, it easily consumes gigabytes of memory). Below please find my test configurations:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.0.27-buster
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
          - name: config
            mountPath: /usr/local/etc/haproxy/haproxy.cfg
            subPath: haproxy.cfg
      volumes:
        - name: config
          configMap:
            name: haproxy
```
```
global
  log stdout format raw local0 info

defaults
  timeout client  60s
  timeout connect 3s
  timeout server  60s
  timeout check   3s
  maxconn 100

frontend acl
  bind            *:10001
  mode            tcp
  default_backend acl

frontend rm
  bind            *:10002
  mode            tcp
  default_backend rm

backend acl
  mode tcp
  option pgsql-check user acl_app
  server pgsql-test-acl pgsql-test-acl:5432 weight 100 check inter 10000

backend rm
  mode tcp
  option pgsql-check user rm_app
  server pgsql-test-rm pgsql-test-rm:5432 weight 100 check inter 10000

```
