### ISSUE TITLE
haproxy reload command does not reload config

### ISSUE THREAD

**Issue by skjbulcher** [docker-library/haproxy#31]
Running an unaltered haproxy 1.6.9 image. The config is set up to proxy requests on port 80 to various other ports on the host (I use haproxy as an http proxy for docker-served webhosts).

**docker-compose.yml**
```
haproxy:
    image: haproxy:1.6.9
    ports:
      - "80:80"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
```

According to the [documentation](https://hub.docker.com/_/haproxy/), I should be able to reload changes to `haproxy.cfg` by running the command `docker kill -s HUP <my-running-haproxy>`.

**Actions taken**

1. Edit haproxy.cfg; add forwarding for a new host, e.g. `newhost`
1. `docker kill -s HUP proxy_haproxy_1`

**Result**

1. docker-compose logs displays: 

        haproxy_1           | <5>haproxy-systemd-wrapper: re-executing on SIGHUP.
        haproxy_1           | <7>haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds -sf 7

1. Visiting `http://newhost` in a browser results in a *503 Service Unavailable* error
1. Issue `docker-compose restart`
1. Visiting `http://newhost` now works

**Expected Result**

1. Visiting `http://newhost` works immediately following the execution of `docker kill -s HUP proxy_haproxy_1`
