### ISSUE TITLE
Error when using docker-compose

### ISSUE THREAD

**Issue by gregorko** [docker-library/haproxy#7]
I get the following error when running haproxy with docker-compose:
```
Recreating opt_haproxy_1...
Cannot start container {hash}: [8] System error: mounting into / is prohibited
```

This is my docker-compose.yml:

```
haproxy:
  image: haproxy:1.5
  ports:
    - "80:80"
  volumes:
    /opt/docker-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
```

Removing the complete volumes section makes no difference.

The same configuration with docker works.
