### ISSUE TITLE
Container exits when using "docker-compose up"

### ISSUE THREAD

**Issue by jl2035** [docker-library/haproxy#87]
Hi,

is this the normal behavior? Shouldn't this container stay up as haproxy is supposed to be a service?

My docker-compose.yml file looks like this:

```
version: '2'
services:
    haproxy:
        image: haproxy:1.7
        ports:
            - 80:80
        expose:
            - 80
        network_mode: host
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
```

Any help would be appreciated.
